### ISSUE TITLE
Identify core version and update / release plan in README

### ISSUE THREAD

**Issue by jeremydouglass** [micycle1/processing-core-4#1]
Given that Processing4 is in alpha, and [core](https://github.com/processing/processing4/tree/master/core) is in active development, it might be nice to identify what snapshot date / commit / version of core each release is based on, and say something in the README about if there is a plan to periodically update.

This seems very useful -- my only concern is that it may lead people to use a very old early alpha version *without realizing that is what they are using*.

**Comment by micycle1** [comment]
The version was labelled in Github releases but it doesn't hurt to include it in the readme too: https://github.com/micycle1/processing-core-4/commit/969f93717498862616fea8631f74b2d299920d68
