### ISSUE TITLE
4.0 beta 1 is out!

### ISSUE THREAD

**Issue by jeremydouglass** [micycle1/processing-core-4#2]
If you would like to update this repo to point at the latest core, 4.0 beta 1 is out.

-  This repo currently: [Processing 4.0 alpha 3](https://github.com/processing/processing4/releases/tag/processing-1272-4.0a3) 2021-01
-  New upstream: [Processing 4.0 beta 1](https://github.com/processing/processing4/releases/tag/processing-1276-4.0b1) 2021-08

Even if not, please consider updating this repo to identify "4.0a3" -- not 4.0.3, which appears to come after the beta, when it really comes 9 months before.

**Comment by micycle1** [comment]
I'm just waiting until https://github.com/processing/processing4/pull/238 is merged. Otherwise think there's been no worthwhile changes to Processing core since 4.0a3. I'll update the name to something more appropriate (4.0bX) then too.

**Comment by micycle1** [comment]
Updated to 4.0b4.
