### ISSUE TITLE
4.1.2 and 4.2: Could not find JOGL

### ISSUE THREAD

**Issue by hamoid** [micycle1/processing-core-4#9]
Hi! I had a program running with 4.1.1. 

If I change the gradle dependency to 4.1.2 I get

    Could not find org.jogamp.jogl:jogl-all:2.4.0-rc-20230123

If I change it to 4.2 I get

    Could not find org.jogamp.jogl:jogl-all-main:2.4.0

In https://mvnrepository.com/artifact/org.jogamp.jogl/jogl-all-main I see only 2.3.2 is available.

**Comment by micycle1** [comment]
The .pom references the https://jogamp.org/deployment/maven/ repository, which is where v2.4.0 is located. 
Not sure why your gradle isn't attempting to pull from here.

**Comment by hamoid** [comment]
Here the project. Is there something missing? It does work with 4.1.1...

[p5GE.zip](https://github.com/micycle1/processing-core-4/files/11450764/p5GE.zip)

**Comment by xlinx** [comment]
`repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven { url 'https://jogamp.org/deployment/maven' }
}

dependencies {
   implementation 'com.github.micycle1:processing-core-4:4.2'
}`

add jogamp repositories. is it the correct way to solve this issue?

**Comment by hamoid** [comment]
Thank you @xlinx ! That makes it build for me. Maybe not ideal to depend on packages outside maven central (in case they stop working some day), but not many other options currently.

And... you studied at TNUA??? I gave a workshop / performance there in 2016! Funny coincidence :-)

**Comment by xlinx** [comment]
> Thank you @xlinx ! That makes it build for me. Maybe not ideal to depend on packages outside maven central (in case they stop working some day), but not many other options currently.
> 
> And... you studied at TNUA??? I gave a workshop / performance there in 2016! Funny coincidence :-)

ur welcome. cool and yes, I've studied at TNAU and also a teacher there in new-media.

**Comment by micycle1** [comment]
Well, Gradle's pretty dumb then.
